services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./currency_app:/currency_app/
    container_name: currency_app
    command: python manage.py runserver 0.0.0.0:8000 --noreload